### ISSUE TITLE
ndk-build throws an exception

### ISSUE THREAD

**Issue by shahasachin** [BrianAberle/XMLFoundation#1]
I am trying to displays android phone screen on desktop. I have downloaded the code, made the changes as described in "Android Studio 2.2 README.txt"  file. When I run ndk-build command in command prompt, thrown warning and exception, listed at the end also screenshot is attached. 

Can you please let me know what step am I missing?

Thanks and regards,
Sachin Shaha

Exception:
Android NDK: WARNING:C:\XMLFoundation\Examples\Android\Server/jni/Android.mk:Server: non-system libraries in linker flags: -lc:\XMLFoundation\Libraries\openssl\bin-androidARM\libssl.a -lc:\XMLFoundation\Libraries\openssl\bin-androidARM\libcrypto.a
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[arm64-v8a] Compile++      : Server <= ServerCore.cpp
In file included from c:\XMLFoundation\Libraries\XMLFoundation\src/..\..\..\Servers\Core\ServerCore.cpp:13:
c:\XMLFoundation\Libraries\XMLFoundation\inc\GlobalInclude.h:41:10: error: 'operator new' takes type size_t
      ('unsigned long') as first parameter
                void * operator new( unsigned int n, const char *pzFile, int nLine, char chUniqueOverload);
                       ^
c:\XMLFoundation\Libraries\XMLFoundation\src/..\..\..\Servers\Core\ServerCore.cpp:518:10: error: format string is not a
      string literal (potentially insecure) [-Werror,-Wformat-security]
                printf(strSrc.Buf());
                       ^~~~~~~~~~~~
c:\XMLFoundation\Libraries\XMLFoundation\src/..\..\..\Servers\Core\ServerCore.cpp:4627:18: error: cast from pointer to
      smaller type 'int' loses information
                int fdCached = (int)g_OutboundConnectCache.RemoveKey(gKey);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\XMLFoundation\Libraries\XMLFoundation\src/..\..\..\Servers\Core\ServerCore.cpp:12344:10: error: format string is not
      a string literal (potentially insecure) [-Werror,-Wformat-security]
        printf( rErr.GetDescription() );
![xmlfoundation exception]
![xmlfoundation exception](https://cloud.githubusercontent.com/assets/20108917/22744555/af7a832e-ee43-11e6-8acf-fc0991f14361.jpg)

**Comment by shahasachin** [comment]
I have already down loaded from dropbox and build it but it is giving same exception...

**Comment by BrianAberle** [comment]
I downloaded the most recent Android Studio 2.3 Beta 3 to test with


I had to make the following changes:

XMLFoundation.project
classpath 'com.android.tools.build:gradle-experimental:0.9.0-beta3'

XMLFLibrary - build.gradle
compileSdkVersion 25
buildToolsVersion "25.0.0"

GApp - build.gradle
compileSdkVersion 25
buildToolsVersion "25.0.0"


I also had to allow Android Studio to configure on demand and download required components.  The build was successful.  In the image above you are using ndk-build however the Android Studio dev environment is used to build GApp and XMLFLibrary.  I hope this helps.


________________________________

**Comment by shahasachin** [comment]
Thanks for your inputs and appreciated prompt reply.

I have successfully build in Android Studio, but throws exception while building libServer.so using ndk-build (while linking files). Am I missing any step please let me know?  

Thanks.

Build message with exception:
---------------------------------
[arm64-v8a] Compile++      : Server <= FileDataSource.cpp
[arm64-v8a] Compile++      : Server <= ObjQueryParameter.cpp
[arm64-v8a] Compile++      : Server <= ProcedureCall.cpp
[arm64-v8a] Compile++      : Server <= Schema.cpp
[arm64-v8a] Compile++      : Server <= SocketHTTPDataSource.cpp
[arm64-v8a] Compile++      : Server <= StackFrameCheck.cpp
[arm64-v8a] Compile++      : Server <= xmlAttribute.cpp
[arm64-v8a] Compile++      : Server <= xmlDataSource.cpp
[arm64-v8a] Compile++      : Server <= xmlElement.cpp
[arm64-v8a] Compile++      : Server <= xmlElementTree.cpp
[arm64-v8a] Compile++      : Server <= XMLException.cpp
[arm64-v8a] Compile++      : Server <= xmlLex.cpp
[arm64-v8a] Compile++      : Server <= xmlObject.cpp
[arm64-v8a] Compile++      : Server <= xmlObjectFactory.cpp
[arm64-v8a] Compile++      : Server <= XMLProcedureDescriptor.cpp
[arm64-v8a] Compile++      : Server <= SwitchBoard.cpp
[arm64-v8a] Compile++      : Server <= DynamicLibrary.cpp
[arm64-v8a] Compile++      : Server <= IntegrationBase.cpp
[arm64-v8a] Compile++      : Server <= IntegrationLanguages.cpp
[arm64-v8a] SharedLibrary  : libServer.so
C:/Androiddev/ndk/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-
android/bin\ld: cannot find -lc:\XMLFoundation\Libraries\openssl\bin-androidARM\libssl.a
C:/Androiddev/ndk/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-
android/bin\ld: cannot find -lc:\XMLFoundation\Libraries\openssl\bin-androidARM\libcrypto.a
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:\XMLFoundation\Examples\Android\Server/obj/local/arm64-v8a/libServer.so] Error 1

**Comment by BrianAberle** [comment]
Check out the docs on Eclipse vs Android Studio, The source tree is setup to build with either development tool.


________________________________

**Comment by BrianAberle** [comment]
It works in the most recent toolsets
